<?php
/**
 * REST API field.
 *
 * @package AudioTranscriber
 */

namespace AudioTranscriber;

defined( 'ABSPATH' ) || exit;

/**
 * Exposes transcripts on the core media endpoint: GET /wp-json/wp/v2/media/<id> -> "audio_transcriber".
 *
 * Headless front ends and other plugins can read transcripts without custom endpoints.
 */
final class Rest_Fields {

	/**
	 * Register hooks.
	 */
	public static function register(): void {
		add_action( 'rest_api_init', array( self::class, 'register_field' ) );
	}

	/**
	 * Register the read-only field.
	 */
	public static function register_field(): void {
		register_rest_field(
			'attachment',
			'audio_transcriber',
			array(
				'get_callback' => array( self::class, 'get_value' ),
				'schema'       => array(
					'description' => __( 'Transcript generated by Audio Transcriber.', 'audio-transcriber' ),
					'type'        => array( 'object', 'null' ),
					'context'     => array( 'view', 'edit' ),
					'readonly'    => true,
					'properties'  => array(
						'status'       => array( 'type' => 'string' ),
						'language'     => array( 'type' => 'string' ),
						'text'         => array( 'type' => 'string' ),
						'segments'     => array(
							'type'  => 'array',
							'items' => array(
								'type'       => 'object',
								'properties' => array(
									'start' => array( 'type' => 'number' ),
									'end'   => array( 'type' => 'number' ),
									'text'  => array( 'type' => 'string' ),
								),
							),
						),
						'captions_url' => array( 'type' => array( 'string', 'null' ) ),
					),
				),
			)
		);
	}

	/**
	 * Field value: null for files that were never transcribed.
	 *
	 * @param array $attachment Attachment data prepared for the response.
	 */
	public static function get_value( array $attachment ): ?array {
		$meta = Meta::get( (int) $attachment['id'] );
		if ( '' === $meta['status'] ) {
			return null;
		}
		// Internal details (job id, error text) stay private to the admin UI.
		return array(
			'status'       => $meta['status'],
			'language'     => $meta['language'],
			'text'         => $meta['text'],
			'segments'     => $meta['segments'],
			'captions_url' => $meta['captions_url'],
		);
	}
}
